/* This folder contains migration files. In the context of a database, a Migration file describes 
 * the existing schema of the database. They may also contain scripts to modify the schema or 
 * insert default data into a database. The schema of a database consists of the tables, their 
 * columns and the relationships between tables, i.e. it describes the topology of the database.
 * Please note that a Database Schema is related to but distinct from a Data Model (See Context.cs
 * in the DbContext folder to learn the difference.) Migrations are a convenient way to alter 
 * your database schema over time in a consistent and easy way. 
 *
 * If tables are added or removed from the database, or if table relationships are modified, the 
 * database schema changes. No further data snapshots can be made until new migration files are 
 * created to describe the database's new schema. "A migration is the new version of database['s 
 * schema]. A schema starts off with nothing in it, and each migration modifies it to add or remove 
 * tables, columns, or entries." (http://edgeguides.rubyonrails.org/active_record_migrations.html) 
 * Once migrations files have been created, snapshots of the data can be made as long as the schema 
 * is not altered.
 * 
 * In IDEs, migrations files for .NET Core projects can be generated by Entity Framework. To do 
 * this, change the Context.cs class in the Providers folder to describe the new schema and then 
 * run the "add-migration" command in the IDE terminal. Based on the new definitions in Context.cs, 
 * Entity Framework will generate new migration files for your database.
 * 
 * Migrations can alter a table, add tables, and delete/drop tables. They can also be used to add 
 * default data to a table.When the migrations are run with the "update-database" command, it will 
 * run all the 'Up' migrations, which can modify the schema, the database, or a table. Runnning this 
 * command "add-migration <migration-name>" will revert any migration run after the migration named 
 * <migration-name>. If this is done, EF will run the 'Down' migrations for those migrations. 
 *
 * Database migrations are mostly done in the development stages of an application, before it 
 * reaches release, since that's when changes to the database are constantly being made, new 
 * features are getting added, and large architectural changes are being made. They are also 
 * typically done when upgrading a database, switching to another database vendor, or moving a 
 * database into the cloud.
 */
 
 

 
 